apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-worker-ms
  labels:
    app: elastic-worker-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-worker-ms
  template:
    metadata:
      labels:
        app: elastic-worker-ms
    spec:
      containers:
        - name: elastic-worker-ms
          image: islamahmad/eaproj-elastic-workerms:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: elastic-worker-ms
            - configMapRef:
                name: services-global
            - configMapRef:
                name: kafka-global

