apiVersion: v1
kind: ConfigMap
metadata:
  name: question-ms
  namespace: default
data:
  MONGODB_HOST: "TODO mongodb-sharded-1573848232.default.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_PASS: "elastic_worker"
  MONGODB_USERNAME: "elastic_worker"
  MONGODB_DATABASE: "elastic_worker"
  MONGODB_AUTH: "elastic_worker"
